"""The Builder's Environment on disk: one file per tool body, rendered modules, the read surface.

A file `env/tools/<name>.py` holds one function `def <name>(self, <args>):` with the body
the model writes, so the file is valid Python on its own and `edit` works on it. `explode`
writes those files from `bodies.json` and seeds a stub for every mined signature with no body,
`regenerate` reads them back into `bodies.json` plus
the rendered `env/tools.py` and `env/data_model.py`, `expose` copies the read surface under
`env/`, and `executor` runs a written body over recorded calls for the gates.

Carried: D155 (the recording is the standard the bodies reproduce), D171 (per-call rows in
the read surface), D224 (no synthetic row is ever written here, only derived ones are read).
"""

from __future__ import annotations

import ast
import json
import shutil
import textwrap
from pathlib import Path
from typing import Any, Callable, Iterable, Optional

from kullback.builder.compile_env import module_source, render_data_model, render_tools
from kullback.builder.sandbox import Sandbox
from kullback.gates.confinement import ALLOWED_IMPORTS, CONTEXT_READS, DENIED_BUILTINS, PROVIDED_HELPERS
from kullback.runner.records import EntitySchema, ToolCall, ToolSig, Trace, as_dict, read_json, write_json

TOOLS_DIR = "tools"
CALLS_DIR = "calls"
TASKS_DIR = "tasks"
BODIES_FILE = "bodies.json"
SIGS_FILE = "tool_sigs.json"
SCHEMA_FILE = "schema.json"

#: The body a tool starts with until the model writes one, the default `render_tools` uses.
STUB_BODY = "raise NotImplementedError"

#: Files at the workdir root the Builder may read, copied under env/ by expose.
READ_FILES = ("schema.json", "tool_sigs.json", "db.json", "canon-rules.json", "vocabulary.json")

#: Past this many names a header line is cut with "and N more"; the gate's refused names fit under it.
HEAD_NAMES = 20


def _listed(names: Iterable[str]) -> str:
    """The names sorted on one line, cut with "and N more" past `HEAD_NAMES`."""
    ordered = sorted(names)
    if len(ordered) <= HEAD_NAMES:
        return ", ".join(ordered)
    return ", ".join(ordered[:HEAD_NAMES]) + f" and {len(ordered) - HEAD_NAMES} more"


_FILE_HEAD = ("# Generated by the harness from the recorded calls. Edit the body in place.\n"
              f"# Imports allowed: {', '.join(sorted(ALLOWED_IMPORTS))}.\n"
              f"# Helpers provided, call by name with no import: {', '.join(sorted(PROVIDED_HELPERS))}.\n"
              f"# Time, randomness and new ids come from the context: {', '.join(CONTEXT_READS)}.\n"
              f"# Names refused: {_listed(DENIED_BUILTINS)}.\n"
              "from typing import Any, Optional\n\n")


def body_of(source: str) -> tuple[str, str]:
    """The (name, body) of the one function `source` holds: body statements, dedented.

    Line numbers come from `ast`, the shape `bodies.json` and `module_source` already use:
    the body is the function's statements sliced out of the source and dedented, so a file
    `explode` wrote reads back to the body it was written from.
    """
    tree = ast.parse(source)
    func = next((node for node in tree.body
                 if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))), None)
    if func is None or not func.body:
        raise ValueError("a tool file holds one function definition with a body")
    lines = source.splitlines(keepends=True)
    start = func.body[0].lineno - 1
    end = func.body[-1].end_lineno or start + 1
    return func.name, textwrap.dedent("".join(lines[start:end])).strip("\n")


def _read_bodies(workdir: Path) -> dict[str, str]:
    raw = read_json(workdir / BODIES_FILE, {})
    if isinstance(raw, dict) and isinstance(raw.get("bodies"), dict):
        raw = raw["bodies"]
    return {name: body for name, body in (raw or {}).items() if isinstance(body, str)}


def _read_sigs(workdir: Path) -> list[ToolSig]:
    raw = read_json(workdir / SIGS_FILE, [])
    return [ToolSig.model_validate(item) for item in raw] if isinstance(raw, list) else []


def _read_schema(workdir: Path) -> EntitySchema:
    return EntitySchema.model_validate(read_json(workdir / SCHEMA_FILE, {}))


def _signature_of(sig: Optional[ToolSig], name: str) -> str:
    """The `def` line a tool file carries, from the mined signature in tool_sigs.json."""
    if sig is None:
        return f"def {name}(self):"
    from kullback.builder.compile_env import _signature

    return _signature(sig).strip()


def _tool_file(name: str, sig: Optional[ToolSig], body: str) -> str:
    text = (body or "pass").strip("\n") or "pass"
    return f"{_FILE_HEAD}{_signature_of(sig, name)}\n" + textwrap.indent(text, "    ") + "\n"


def explode(workdir: Any) -> list[str]:
    """Write `env/tools/<name>.py` for every tool whose file is missing.

    A `bodies.json` entry is written with its body; a mined signature in `tool_sigs.json`
    with no body is seeded with the stub `raise NotImplementedError`, so every tool has a
    file once the world is derived. Files the model already edited are never touched: only
    missing ones are written. Returns the names written.
    """
    root = Path(workdir)
    bodies = _read_bodies(root)
    sigs = {sig.name: sig for sig in _read_sigs(root)}
    for name in sigs:
        bodies.setdefault(name, STUB_BODY)
    written = []
    for name, body in bodies.items():
        path = root / "env" / TOOLS_DIR / f"{name}.py"
        if path.is_file():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_tool_file(name, sigs.get(name), body), encoding="utf-8")
        written.append(name)
    return written


def is_stub(path: Path) -> bool:
    """Whether the tool file at `path` still holds only the stub body."""
    try:
        return body_of(path.read_text(encoding="utf-8"))[1].strip() == STUB_BODY
    except (OSError, SyntaxError, ValueError):
        return False


def regenerate(workdir: Any, env: Any = None) -> dict[str, Any]:
    """Read every `env/tools/*.py` back into `bodies.json`, `env/tools.py`, `env/data_model.py`.

    `bodies.json` keeps the shape the build writes today (a flat name to body dict, what
    `BuiltEnvironment` reads); the two rendered files come from `render_tools` and
    `render_data_model`, so code owns everything but the body. Returns the bodies and paths.
    """
    root = Path(workdir)
    env_root = Path(env) if env is not None else root / "env"
    schema = _read_schema(root)
    sigs = _read_sigs(root)
    bodies: dict[str, str] = {}
    tools_dir = env_root / TOOLS_DIR
    if tools_dir.is_dir():
        for path in sorted(tools_dir.glob("*.py")):
            try:
                name, body = body_of(path.read_text(encoding="utf-8"))
            except (OSError, SyntaxError, ValueError):
                continue
            bodies[name] = body
    ordered = {sig.name: bodies[sig.name] for sig in sigs if sig.name in bodies}
    ordered.update({name: bodies[name] for name in sorted(bodies) if name not in ordered})
    write_json(root / BODIES_FILE, ordered)
    tools_path = env_root / "tools.py"
    tools_path.parent.mkdir(parents=True, exist_ok=True)
    tools_path.write_text(render_tools(schema, sigs, ordered), encoding="utf-8")
    model_path = env_root / "data_model.py"
    model_path.write_text(render_data_model(schema), encoding="utf-8")
    return {"bodies": ordered, "paths": [BODIES_FILE, "env/tools.py", "env/data_model.py"]}


def _held_out_run_ids(workdir: Path) -> set[str]:
    anchor = read_json(workdir / "anchor.json", None)
    held: set[str] = set()
    if isinstance(anchor, dict):
        for runs in (anchor.get("held_out") or {}).values():
            for run_id in runs or []:
                held.add(str(run_id))
    return held


def _trace_calls(path: Path) -> list[ToolCall]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    if isinstance(raw, dict) and isinstance(raw.get("tool_calls"), list):
        try:
            return list(Trace.model_validate(raw).tool_calls)
        except ValueError:
            pass
    calls = raw.get("tool_calls") if isinstance(raw, dict) else raw
    out = []
    if isinstance(calls, list):
        for item in calls:
            try:
                out.append(ToolCall.model_validate(item))
            except ValueError:
                continue
    return out


def expose(workdir: Any) -> dict[str, Any]:
    """Copy the read surface under `env/`: the world files, the Tasks, the shown calls.

    Held-out calls are never copied (a call whose trace the anchor held out stays out of
    the Builder's root), and no Verifier, probe, run or gate artifact is copied: the read
    surface is world rows and shown recordings only. Returns what was copied.
    """
    root = Path(workdir)
    env = root / "env"
    copied: dict[str, Any] = {"files": [], "tasks": [], "calls": {}}
    for name in READ_FILES:
        source = root / name
        if source.is_file():
            target = env / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            copied["files"].append(name)
    tasks_dir = root / TASKS_DIR
    if tasks_dir.is_dir():
        for path in sorted(tasks_dir.glob("*.json")):
            if path.name == "tasks.json":
                continue
            target = env / TASKS_DIR / path.name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
            copied["tasks"].append(path.name)
    sigs = _read_sigs(root)
    if sigs and (root / "traces").is_dir():
        held = _held_out_run_ids(root)
        by_tool: dict[str, list[dict]] = {sig.name: [] for sig in sigs}
        for path in sorted((root / "traces").glob("*.json")):
            for call in _trace_calls(path):
                if call.name in by_tool and str(call.trace_id or "") not in held:
                    by_tool[call.name].append(as_dict(call))
        for name, rows in by_tool.items():
            target = env / CALLS_DIR / f"{name}.jsonl"
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("w", encoding="utf-8") as handle:
                for row in rows:
                    handle.write(json.dumps(row, sort_keys=True) + "\n")
            copied["calls"][name] = len(rows)
    return copied


def _read_db(workdir: Path, db: Any) -> dict:
    if isinstance(db, dict):
        return db
    for name in ("db.json", "env/db.json"):
        found = read_json(workdir / name, None)
        if isinstance(found, dict):
            return found
    return {}


def render_module(workdir: Any, env: Any = None, source: Any = None) -> str:
    """The module the Runner will load: every body in `env/tools/*.py`, `source` overlaid.

    The one rendering the write gates and the sandbox share, so a write is ruled on the same
    text `load_toolkit` confines. A `source` that does not parse is left out; the parses gate
    rules on it.
    """
    root = Path(workdir)
    env_root = Path(env) if env is not None else root / "env"
    bodies: dict[str, str] = {}
    tools_dir = env_root / TOOLS_DIR
    if tools_dir.is_dir():
        for path in sorted(tools_dir.glob("*.py")):
            try:
                name, body = body_of(path.read_text(encoding="utf-8"))
            except (OSError, SyntaxError, ValueError):
                continue
            bodies[name] = body
    if isinstance(source, str) and source.strip():
        try:
            name, body = body_of(source)
        except (SyntaxError, ValueError):
            name, body = "", ""
        if name:
            bodies[name] = body
    return module_source(_read_schema(root), _read_sigs(root), bodies)


def executor(workdir: Any, env: Any = None) -> Callable[[Any, Iterable[ToolCall], Any], list[dict]]:
    """The gates' `execute(source, calls, db)`: the current bodies as one module, run in the sandbox.

    Bodies come from `env/tools/*.py` as `regenerate` reads them, overlaid with the written
    source itself, so a ruling measures the file the model just wrote. One sandbox-shaped
    result dict per call. The returned callable carries `render(source)`, the same module
    text, which the confinement gate reads. Carried: D122 (the sandbox is where model-written
    code runs).
    """
    root = Path(workdir)

    def render(source: Any) -> str:
        return render_module(root, env, source)

    def execute(source: Any, calls: Iterable[ToolCall], db: Any) -> list[dict]:
        sandbox = Sandbox(render(source), _read_db(root, db), root)
        return [dict(row) for row in sandbox.run(list(calls))]

    execute.render = render  # type: ignore[attr-defined]
    return execute


__all__ = ["BODIES_FILE", "CALLS_DIR", "READ_FILES", "SCHEMA_FILE", "SIGS_FILE", "STUB_BODY", "TASKS_DIR",
           "TOOLS_DIR", "body_of", "executor", "explode", "expose", "is_stub", "regenerate",
           "render_module"]
