"""The Builder session: writes are ruled with rows, the read surface is fenced, the bus is gapless."""

from __future__ import annotations

import asyncio
import json
import os
from types import SimpleNamespace

import pytest
from pydantic import ValidationError

from kullback.agent.events import ToolExecutionEnd as ToolEnd
from kullback.ai.provider import TestModel
from kullback.builder import domain_tools as domain_tools_mod
from kullback.builder import session as session_mod
from kullback.builder.domain_tools import NoteArgs
from kullback.examiner import domain_tools as exam_tools
from kullback.runner import budget
from kullback.runner.records import RawPtr, ToolCall, Trace, Turn
from tests.builder.session_fixtures import error, priced, reply
from tests.episode.invented import write_env

PTR = RawPtr(file_hash="f" * 64, sim_index=0, msg_index=0)

SMUDGED_BODY = (
    "row = self.db.widgets.get(widget_id)\n"
    "if row is None:\n"
    "    raise KeyError(widget_id)\n"
    'row.label = "smudged"\n'
    'return {"widget_id": widget_id, "label": "smudged"}'
)

TOOL_FILE = ("# Generated by the harness from the recorded calls. Edit the body in place.\n"
             "from typing import Any, Optional\n\n"
             "def rename_widget(self, widget_id, label):\n"
             "    row = self.db.widgets.get(widget_id)\n"
             "    if row is None:\n"
             "        raise KeyError(widget_id)\n"
             '    row.label = "smudged"\n'
             '    return {"widget_id": widget_id, "label": "smudged"}\n')


STOP_LINE = "I cannot go further: the rename body still differs from its recorded calls."


def _workdir(tmp_path):
    root = write_env(tmp_path / "work")
    # The mined arguments, as derive writes them: the rendered module takes its signature from here.
    sigs = json.loads((root / "tool_sigs.json").read_text(encoding="utf-8"))
    for sig in sigs:
        sig["args_fields"] = [{"name": name, "types": ["str"], "optional": False}
                              for name in sig.get("args_schema", {}).get("properties", {})]
    (root / "tool_sigs.json").write_text(json.dumps(sigs), encoding="utf-8")
    traces = root / "traces"
    traces.mkdir(parents=True, exist_ok=True)
    turns = [
        Turn(idx=0, role="assistant", content="Hi! How can I help?", raw_ptr=PTR),
        Turn(idx=1, role="user", content="Give widget w1 the label striped.", raw_ptr=PTR),
        Turn(idx=2, role="assistant", content=None, tool_call_ids=["c1"], raw_ptr=PTR),
        Turn(idx=3, role="tool", content='{"widget_id": "w1"}', tool_call_ids=["c1"],
             raw_ptr=PTR),
        Turn(idx=4, role="assistant", content=None, tool_call_ids=["c2"], raw_ptr=PTR),
        Turn(idx=5, role="tool", content='{"widget_id": "w1"}', tool_call_ids=["c2"],
             raw_ptr=PTR),
        Turn(idx=6, role="assistant", content="Done.", raw_ptr=PTR),
        Turn(idx=7, role="user", content="Thanks, that is the right label.", raw_ptr=PTR),
    ]
    calls = [
        ToolCall(id="c1", name="describe_widget", args={"widget_id": "w1"},
                 result={"widget_id": "w1", "label": "plain"}, raw_ptr=PTR, trace_id="rec1"),
        ToolCall(id="c2", name="rename_widget", args={"widget_id": "w1", "label": "striped"},
                 result={"widget_id": "w1", "label": "striped"}, raw_ptr=PTR, trace_id="rec1"),
    ]
    trace = Trace(trace_id="rec1", raw_hash="r" * 64, ingest_version="1", source="test",
                  turns=turns, tool_calls=calls, raw_ptr=PTR)
    (traces / "rec1.json").write_text(json.dumps(trace.model_dump(mode="json", by_alias=True)),
                                      encoding="utf-8")
    return root


def _scripted_session(tmp_path):
    root = _workdir(tmp_path)
    model = TestModel([
        reply("Writing the body.",
              ("write", {"path": "tools/rename_widget.py", "content": TOOL_FILE})),
        reply("Trying a read-only path.", ("write", {"path": "schema.json", "content": "{}"})),
        reply("Trying the shell.", ("bash", {"command": "cat ../traces/rec1.json"})),
        reply("Reading the calls.", ("read", {"path": "calls/rename_widget.jsonl"})),
        reply("Done."),
        reply(STOP_LINE),
    ])
    ends = []
    result = session_mod.build(
        root, model,
        subscribers=[lambda event: ends.append(event) if isinstance(event, ToolEnd) else None])
    return root, result, [event for event in ends if isinstance(event, ToolEnd)]


def test_a_tool_write_is_ruled_with_a_fidelity_ruling_carrying_rows(tmp_path):
    root, _, ends = _scripted_session(tmp_path)
    write = next(end for end in ends if end.tool_name == "write" and not end.is_error)
    rulings = write.result.details.get("rulings") or []
    assert rulings, "a write under tools/ draws rulings"
    fidelity = [ruling for ruling in rulings if "fidelity" in ruling["name"]]
    assert fidelity, f"a fidelity ruling is among {[r['name'] for r in rulings]}"
    assert fidelity[0]["rows"], "the fidelity ruling carries per-call rows"
    assert not fidelity[0]["accepted"]
    assert (root / "env" / "tools.py").read_text(encoding="utf-8").count("smudged") >= 1
    assert "smudged" in json.loads((root / "bodies.json").read_text(encoding="utf-8"))["rename_widget"]


def test_a_write_outside_the_four_directories_is_refused(tmp_path):
    _, _, ends = _scripted_session(tmp_path)
    refused = [end for end in ends if end.tool_name == "write" and end.is_error]
    assert len(refused) == 1
    assert "schema.json" in refused[0].result.content


def test_a_shell_step_above_the_root_is_refused(tmp_path):
    _, _, ends = _scripted_session(tmp_path)
    refused = [end for end in ends if end.tool_name == "bash"]
    assert len(refused) == 1 and refused[0].is_error


def test_a_read_of_the_exposed_calls_works(tmp_path):
    _, _, ends = _scripted_session(tmp_path)
    read = next(end for end in ends if end.tool_name == "read")
    assert not read.is_error
    assert "c2" in read.result.content


def test_the_session_ends_when_the_model_answers_without_a_tool_call(tmp_path):
    _, result, _ = _scripted_session(tmp_path)
    assert result["stopped"] == "no tool call"
    assert (result["trusted"], result["refused"], result["open"]) == (0, 0, 1)
    assert [row["task_id"] for row in result["status"]["tasks"]] == ["widget_task"]
    assert result["spend"] == 0.0
    assert result["turns"] == 6
    assert result["last_line"] == STOP_LINE
    assert result["continued"] == 1


def test_the_ceiling_cancels_after_the_tool_call_that_crossed_it(tmp_path):
    from kullback.runner import budget as budget_mod

    root = _workdir(tmp_path)
    crossed = []

    def cross(event):
        if isinstance(event, ToolEnd) and not crossed:
            crossed.append(event)
            totals = budget_mod.empty_totals()
            totals["total"]["usd"] = 5.0
            totals["total"]["calls"] = 1
            budget_mod.save_totals(root, totals)

    model = TestModel([
        reply("Writing the body.",
              ("write", {"path": "tools/rename_widget.py", "content": TOOL_FILE})),
        reply("Reading the calls.", ("read", {"path": "calls/rename_widget.jsonl"})),
        reply("Never reached."),
    ])
    result = session_mod.build(root, model, ceiling_usd=0.01, subscribers=[cross])
    assert result["stopped"] == "ceiling"
    assert result["spend"] == 5.0
    assert model.index == 1


def test_the_bus_holds_the_events_in_gapless_order(tmp_path):
    root, _, _ = _scripted_session(tmp_path)
    lines = (root / "bus.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(lines) > 0
    seqs = [json.loads(line)["seq"] for line in lines]
    assert seqs == list(range(1, len(lines) + 1))


def test_build_hands_examine_the_judge_probe_and_reroll_models(tmp_path, monkeypatch):
    from kullback.examiner import session as examiner_session

    seen = {}

    def examine(workdir, *, task_ids=None, model=None, judge_model=None, probe_model=None,
                reroll_model=None, **kwargs):
        seen.update(judge_model=judge_model, probe_model=probe_model, reroll_model=reroll_model)
        return []

    monkeypatch.setattr(examiner_session, "examine", examine)
    root = _workdir(tmp_path)
    model = TestModel([reply("Examining.", ("examine", {})), reply("Done.")])
    judge, probe, reroll = object(), object(), object()
    session_mod.build(root, model, judge_model=judge, probe_model=probe, reroll_model=reroll)
    assert seen == {"judge_model": judge, "probe_model": probe, "reroll_model": reroll}


def test_build_hands_the_caller_the_live_harness_before_the_first_model_turn(tmp_path):
    """The screen runs the session on another thread and steers it; the seam is the harness itself,
    handed over before the model is first asked, and the return value is unchanged."""
    root = _workdir(tmp_path)
    model = TestModel([reply("Done."), reply(STOP_LINE)])
    seen = []

    def on_harness(harness):
        seen.append((harness, len(model.calls)))
        harness.steer("Read the calls first.")

    result = session_mod.build(root, model, on_harness=on_harness)
    assert len(seen) == 1 and seen[0][1] == 0
    assert result["stopped"] == "no tool call" and result["last_line"] == STOP_LINE
    first_prompt = model.calls[0]["messages"]
    assert any("Read the calls first." in str(message.get("content")) for message in first_prompt)


def test_a_provider_error_on_the_last_turn_is_reported_as_an_error_stop(tmp_path):
    result = session_mod.build(_workdir(tmp_path), error("HTTP 400: the endpoint refused the request"))
    assert result["stopped"] == "error"
    assert "HTTP 400: the endpoint refused the request" in result["last_line"]


def test_a_build_whose_replies_carry_usage_reports_the_spend_and_one_ledger_call_per_turn(tmp_path):
    root = _workdir(tmp_path)
    model = TestModel([
        priced(reply("Reading the calls.", ("read", {"path": "calls/rename_widget.jsonl"}))),
        priced(reply("Done.")),
        priced(reply(STOP_LINE)),
    ], name=next(iter(budget.PRICES)))
    result = session_mod.build(root, model)
    assert result["spend"] > 0
    stage = budget.load_totals(root)["stages"][session_mod.CEILING_STAGE]
    assert stage["calls"] == result["turns"] == 3
    assert stage["usd"] == result["spend"]


def test_the_ceiling_stops_a_build_once_its_priced_usage_reaches_it(tmp_path):
    root = _workdir(tmp_path)
    model = TestModel([
        priced(reply("Reading the calls.", ("read", {"path": "calls/rename_widget.jsonl"})),
               input=1_000_000),
        priced(reply("Never reached.")),
    ], name=next(iter(budget.PRICES)))
    result = session_mod.build(root, model, ceiling_usd=0.01)
    assert result["stopped"] == "ceiling"
    assert result["spend"] >= 0.01
    assert model.index == 1


def test_the_opening_names_derive_world_when_traces_are_stored_and_no_world_is(tmp_path):
    root = _workdir(tmp_path)
    (root / "schema.json").unlink()
    (root / "tool_sigs.json").unlink()
    opening = session_mod.opening(root)
    assert opening.startswith("1 traces are stored and the world is not derived: call derive_world first.")
    assert opening.endswith(session_mod.OPENING)


def test_the_opening_names_the_stubs_when_the_world_is_derived_and_every_body_is_one(tmp_path):
    root = _workdir(tmp_path)
    model = TestModel([reply("Done.")])
    session_mod.build(root, model)
    opening = session_mod.opening(root)
    assert opening.startswith("The world is derived and every body is a stub (2 of 2): "
                              "write each body from its calls, then replay.")
    assert opening in (root / "sessions" / "builder.jsonl").read_text(encoding="utf-8").replace("\\n", "\n")


def test_the_opening_says_every_path_is_relative_to_the_env_root():
    assert "every path is relative to it" in session_mod.OPENING
    assert "tools/, calls/, tasks/" in session_mod.OPENING
    assert "Begin in your root env/" not in session_mod.OPENING


def test_a_stop_with_a_task_open_draws_one_follow_up_with_the_counts_and_the_answer_ends_it(tmp_path):
    root = _workdir(tmp_path)
    model = TestModel([reply("Done."), reply(STOP_LINE)])
    result = session_mod.build(root, model, ceiling_usd=5.0)
    assert (result["stopped"], result["continued"], result["turns"]) == ("no tool call", 1, 2)
    follow_up = str(model.calls[1]["messages"][-1]["content"])
    assert follow_up.startswith("1 Tasks are open, 0 trusted, 0 refused; 0.0000 USD spent of the 5.0000 USD ceiling.")
    assert "Replay every Task, examine the confirmed ones, run them" in follow_up
    assert result["last_line"] == STOP_LINE


def test_a_model_that_keeps_working_after_each_follow_up_gets_at_most_the_bounded_number(tmp_path):
    root = _workdir(tmp_path)
    read = ("read", {"path": "calls/rename_widget.jsonl"})
    model = TestModel([reply("Reading.", read), reply("Done.")], loop=True)
    result = session_mod.build(root, model)
    assert result["continued"] == session_mod.CONTINUATIONS
    assert result["stopped"] == "no tool call"
    assert result["turns"] == 2 * (session_mod.CONTINUATIONS + 1)


def test_a_stop_when_every_task_is_refused_draws_no_follow_up(tmp_path):
    root = _workdir(tmp_path)
    refusals = root / "env" / "refusals"
    refusals.mkdir(parents=True, exist_ok=True)
    (refusals / "widget_task.json").write_text(json.dumps({"reason": "no frontier Run finished"}),
                                               encoding="utf-8")
    model = TestModel([reply("Done.")])
    result = session_mod.build(root, model)
    assert (result["refused"], result["open"]) == (1, 0)
    assert (result["stopped"], result["continued"], result["turns"]) == ("no tool call", 0, 1)


def test_an_error_stop_draws_no_follow_up(tmp_path):
    result = session_mod.build(_workdir(tmp_path), error("HTTP 400: the endpoint refused the request"))
    assert (result["stopped"], result["continued"]) == ("error", 0)


def test_a_stop_at_the_ceiling_draws_no_follow_up():
    status = {"tasks": [{"task_id": "t", "state": "open", "reason": ""}]}
    assert session_mod.continuation(status, 5.0, 5.0) is None
    assert session_mod.continuation(status, 1.0, None).startswith("1 Tasks are open")


def _note_tool(root):
    (tool,) = [t for t in domain_tools_mod.domain_tools(workdir=root) if t.name == "note_task"]
    return tool


def _task_workdir(tmp_path):
    (tmp_path / "tasks").mkdir(parents=True)
    (tmp_path / "tasks" / "t1.json").write_text("{}", encoding="utf-8")
    return tmp_path


def test_the_note_tool_refuses_a_note_carrying_an_atom_and_writes_a_plain_one(tmp_path):
    root = _task_workdir(tmp_path)
    tool = _note_tool(root)
    with pytest.raises(ValidationError):
        NoteArgs(task_id="t1", reason="outcome_not_in_state", sentence="x", atom={"id": "w0"})
    with pytest.raises(ValueError, match="never an atom"):
        asyncio.run(tool.execute(NoteArgs(task_id="t1", reason="outcome_not_in_state",
                                          sentence='demand {"kind": "write"} instead')))
    result = asyncio.run(tool.execute(NoteArgs(task_id="t1", reason="outcome_not_in_state",
                                               sentence="the answer is only said, never written.")))
    assert result.note["reason"] == "outcome_not_in_state"
    assert exam_tools.open_note(root, "t1") == result.note


@pytest.mark.parametrize("task_id", ["../replays", "t1/../../replays", "/tmp/replays", "t2"])
def test_the_note_tool_refuses_an_id_that_is_not_a_task_and_leaves_the_file_it_aimed_at(tmp_path, task_id):
    root = _task_workdir(tmp_path)
    (root / "replays.json").write_text('{"kept": true}', encoding="utf-8")
    with pytest.raises(ValueError, match="unknown Task"):
        asyncio.run(_note_tool(root).execute(NoteArgs(task_id=task_id, reason="outcome_not_in_state",
                                                      sentence="the answer is only said, never written.")))
    assert (root / "replays.json").read_text(encoding="utf-8") == '{"kept": true}'
    assert not (root / exam_tools.NOTES_DIR).exists()


def test_a_task_with_an_open_note_cannot_be_refused_until_the_examiner_rules(tmp_path):

    root = _task_workdir(tmp_path)
    hook = session_mod.refusal_waits_for_note(root)
    refusal = SimpleNamespace(name="write", arguments={"path": "refusals/t1.json", "content": "{}"})
    other = SimpleNamespace(name="write", arguments={"path": "refusals/t2.json", "content": "{}"})
    assert hook(refusal) is None, "no note, no block"
    exam_tools.write_note(root, "t1", "intent_contradicts_reference", "the Intent asks for another item.")
    with pytest.raises(PermissionError, match="open note"):
        hook(refusal)
    assert hook(other) is None, "an open note blocks only its own Task"
    exam_tools.rule_note(root, "t1", "finding", "builder_right", "the Reference answered another Intent")
    assert hook(refusal) is None


def test_the_builders_opening_shows_the_examiners_ruling_on_its_note(tmp_path):
    root = _task_workdir(tmp_path)
    exam_tools.write_note(root, "t1", "needs_action_record", "the hand off leaves no row to check.")
    assert "t1: needs_action_record: the hand off leaves no row to check. (open)" in session_mod.opening(root)
    exam_tools.rule_note(root, "t1", "finding", "builder_wrong", "the hand off writes a ticket row")
    ruled = exam_tools.read_json(exam_tools.ruling_path(root, "t1"))
    assert ruled["verdict"] == "builder_wrong"
    assert ("t1: needs_action_record: the hand off leaves no row to check. (ruled by finding, builder_wrong: "
            "the hand off writes a ticket row)") in session_mod.opening(root)
    assert session_mod.opening(root).endswith(session_mod.OPENING)


def test_a_build_is_steerable_through_its_bus_from_outside_the_caller(tmp_path):
    """Neither the harness nor on_harness is used here: the nudge goes on the workdir's bus, as it
    would from another process, and the session's bridge queues it before the next model turn."""
    from kullback.agent import steer

    root = _workdir(tmp_path)
    model = TestModel([reply("Reading.", ("read", {"path": "calls/rename_widget.jsonl"})),
                       reply("Done."), reply(STOP_LINE)])
    acks = []

    def on_event(event):
        if event.type == "tool_execution_start" and not acks:
            acks.append(steer.wait_for_ack(root, steer.request(root, "nudge", "Read the schema next.",
                                                               session=str(os.getpid())), 5))

    session_mod.build(root, model, subscribers=[on_event])
    assert acks[0] is not None and acks[0].outcome == "queued"
    assert any("Read the schema next." in str(message.get("content")) for message in model.calls[1]["messages"])


def test_a_stop_through_the_bus_after_a_run_ended_starts_no_continuation(tmp_path):
    """The first run ends with no tool call while Tasks are open, so a continuation would follow.
    The stop lands as that run ends, when there is no run left to cancel, and the session ends."""
    from kullback.agent import steer

    root = _workdir(tmp_path)
    model = TestModel([reply("Done."), reply(STOP_LINE)])
    acks = []

    def on_event(event):
        if event.type == "agent_end" and not acks:
            acks.append(steer.wait_for_ack(root, steer.request(root, "stop",
                                                               session=str(os.getpid())), 5))

    result = session_mod.build(root, model, subscribers=[on_event])
    assert acks[0] is not None and acks[0].outcome == "cancel_asked"
    assert len(model.calls) == 1
    assert result["stopped"] == "cancelled" and result["continued"] == 0
