"""One invented Environment on disk: widgets with a read and a write tool.

Nothing here names a corpus, a tool or a customer: the domain is made up so the interface tests
prove the harness, not the data.
"""

from __future__ import annotations

import json
from pathlib import Path

DATA_MODEL = '''"""Generated by the Harness from the customer's traces. Do not edit by hand."""
# Annotations stay eager: the gates exec this module without registering it in sys.modules, so a
# postponed annotation would have no module globals to resolve against.
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Widget(BaseModel):
    """One row of widgets."""
    widget_id: Optional[Any] = Field(default=None)
    label: Optional[Any] = Field(default=None)


class DomainDB(BaseModel):
    """The customer's world as the traces show it."""
    widgets: Dict[str, Widget] = Field(default_factory=dict)

    @classmethod
    def load(cls, path):
        """Load the emitted db.json."""
        import json

        with open(path, encoding="utf-8") as handle:
            return cls.model_validate(json.load(handle))
'''

TOOLS = '''"""Generated by the Harness from the customer's traces. Do not edit by hand."""
from typing import Any, Optional

from data_model import DomainDB, Widget


class _ToolKitBase:
    def __init__(self, db):
        self.db = db


class ToolType:
    READ = "read"
    WRITE = "write"
    GENERIC = "generic"


def is_tool(tool_type):
    def decorate(func):
        func.__tool_type__ = tool_type
        return func

    return decorate


class DomainTools(_ToolKitBase):
    """Every tool mined from the customer's traces."""

    def __init__(self, db) -> None:
        super().__init__(db)
        self.db = db

    @is_tool(ToolType.READ)
    def describe_widget(self, widget_id: str) -> Any:
        """The customer's describe_widget tool, as the traces show it.

        Args:
            widget_id: str

        Returns:
            widget_id, label
        """
        row = self.db.widgets.get(widget_id)
        if row is None:
            raise KeyError(widget_id)
        return {"widget_id": widget_id, "label": row.label}

    @is_tool(ToolType.WRITE)
    def rename_widget(self, widget_id: str, label: str) -> Any:
        """The customer's rename_widget tool, as the traces show it.

        Args:
            widget_id: str
            label: str

        Returns:
            widget_id, label
        """
        row = self.db.widgets.get(widget_id)
        if row is None:
            raise KeyError(widget_id)
        row.label = label
        return {"widget_id": widget_id, "label": label}
'''


def write_env(root: Path, *, task_id: str = "widget_task", run_id: str = "rec1",
              with_rules: bool = True, with_verifier: bool = True,
              verifier_atoms: list | None = None) -> Path:
    """The invented workdir: schema, signatures, db, toolkit, overlay, Task, rules, Verifier."""
    (root / "env").mkdir(parents=True, exist_ok=True)
    (root / "tasks").mkdir(parents=True, exist_ok=True)
    (root / "overlays").mkdir(parents=True, exist_ok=True)
    (root / "verifiers").mkdir(parents=True, exist_ok=True)
    (root / "environment.json").write_text(json.dumps({"env_id": "widgets-1"}), encoding="utf-8")
    (root / "schema.json").write_text(json.dumps({
        "tables": ["widgets"],
        "columns": [
            {"table": "widgets", "name": "widget_id", "class": "hard"},
            {"table": "widgets", "name": "label", "class": "semantic"},
        ],
    }), encoding="utf-8")
    (root / "tool_sigs.json").write_text(json.dumps([
        {"name": "describe_widget", "description": "look one widget up",
         "args_schema": {"type": "object", "properties": {"widget_id": {"type": "string"}}},
         "kind": "read", "unclassified": False},
        {"name": "rename_widget", "description": "give one widget a new label",
         "args_schema": {"type": "object", "properties": {"widget_id": {"type": "string"},
                                                          "label": {"type": "string"}}},
         "kind": "write", "unclassified": False},
    ]), encoding="utf-8")
    (root / "bodies.json").write_text(json.dumps({}), encoding="utf-8")
    (root / "db.json").write_text(json.dumps({"widgets": {"w1": {"widget_id": "w1",
                                                                  "label": "plain"}}}),
                                  encoding="utf-8")
    (root / "env" / "data_model.py").write_text(DATA_MODEL, encoding="utf-8")
    (root / "env" / "tools.py").write_text(TOOLS, encoding="utf-8")
    (root / "env" / "policy.md").write_text("Be helpful with widgets.", encoding="utf-8")
    (root / "canon-rules.json").write_text(json.dumps({}), encoding="utf-8")
    (root / "tasks" / f"{task_id}.json").write_text(json.dumps({
        "id": task_id, "run_ids": [run_id], "intent": "give widget w1 the label striped",
    }), encoding="utf-8")
    (root / "overlays" / f"{task_id}.json").write_text(json.dumps({
        "overlay": {"task_id": task_id, "rows": [], "steps": []},
        "values": {},
    }), encoding="utf-8")
    if with_rules:
        (root / "user_rules").mkdir(parents=True, exist_ok=True)
        (root / "user_rules" / f"{run_id}.json").write_text(json.dumps({
            "facts": [{"field": "widget_id", "value": "w1"},
                      {"field": "label", "value": "striped"}],
        }), encoding="utf-8")
    if with_verifier:
        atoms = verifier_atoms if verifier_atoms is not None else [
            {"id": "a1", "kind": "required", "predicate_src": "wrote('rename_widget')",
             "target": {"kind": "write"}},
        ]
        (root / "verifiers" / f"{task_id}.json").write_text(json.dumps({
            "task_id": task_id, "atoms": atoms, "verifier_version": "1",
        }), encoding="utf-8")
    return root


SCRIPTED_RENAME = [
    {"content": None, "tool_calls": [{"id": "c1", "name": "describe_widget",
                                      "arguments": {"widget_id": "w1"}}]},
    {"content": None, "tool_calls": [{"id": "c2", "name": "rename_widget",
                                      "arguments": {"widget_id": "w1", "label": "striped"}}]},
    {"content": "done", "tool_calls": []},
]
