"""run_record reads the recorded file, so later writes cannot rewrite earlier results (G1).

Needs the step-split patch (docs/frozen-patches/step-split.patch): the interface steps the world
through `advance`, so this module skips unless the patch is applied.
"""

from __future__ import annotations

import json

import pytest

from kullback.runner import loop

pytestmark = pytest.mark.skipif(
    not (hasattr(loop, "ask") and hasattr(loop, "advance")),
    reason="needs the step-split patch",
)

from kullback.runner.world import BuiltEnvironment, Episode, EpisodeError  # noqa: E402
from tests.episode.invented import write_env  # noqa: E402

DATA_MODEL_UNCOPYABLE = '''"""Generated by the Harness from the customer's traces. Do not edit by hand."""
# Annotations stay eager: the gates exec this module without registering it in sys.modules, so a
# postponed annotation would have no module globals to resolve against.
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Widget(BaseModel):
    """One row of widgets."""
    widget_id: Optional[Any] = Field(default=None)
    label: Optional[Any] = Field(default=None)

    def __deepcopy__(self, memo):
        """A live row cannot be copied once a later write has mutated it."""
        if self.label == "striped":
            raise RuntimeError("the live row must stay in the toolkit")
        return Widget(widget_id=self.widget_id, label=self.label)


class DomainDB(BaseModel):
    """The customer's world as the traces show it."""
    widgets: Dict[str, Widget] = Field(default_factory=dict)

    @classmethod
    def load(cls, path):
        """Load the emitted db.json."""
        import json

        with open(path, encoding="utf-8") as handle:
            return cls.model_validate(json.load(handle))
'''


def _write_alias_env(root):
    (root / "env" / "tools.py").write_text(ALIAS_TOOLS, encoding="utf-8")
    (root / "env" / "data_model.py").write_text(DATA_MODEL_UNCOPYABLE, encoding="utf-8")

ALIAS_TOOLS = '''"""Generated by the Harness from the customer's traces. Do not edit by hand."""
from typing import Any, Optional

from data_model import DomainDB, Widget


class _ToolKitBase:
    def __init__(self, db):
        self.db = db


class ToolType:
    READ = "read"
    WRITE = "write"
    GENERIC = "generic"


def is_tool(tool_type):
    def decorate(func):
        func.__tool_type__ = tool_type
        return func

    return decorate


class DomainTools(_ToolKitBase):
    """Every tool mined from the customer's traces."""

    def __init__(self, db) -> None:
        super().__init__(db)
        self.db = db

    @is_tool(ToolType.READ)
    def describe_widget(self, widget_id: str) -> Any:
        row = self.db.widgets.get(widget_id)
        if row is None:
            raise KeyError(widget_id)
        return row

    @is_tool(ToolType.WRITE)
    def rename_widget(self, widget_id: str, label: str) -> Any:
        row = self.db.widgets.get(widget_id)
        if row is None:
            raise KeyError(widget_id)
        row.label = label
        return {"widget_id": widget_id, "label": label}
'''


def test_run_record_matches_the_recorded_file(tmp_path):
    from kullback.runner.records import as_dict
    from kullback.runner.verdict import load_run

    root = write_env(tmp_path / "root")
    _write_alias_env(root)
    episode = Episode(BuiltEnvironment(root), outdir=tmp_path / "out")
    episode.reset("widget_task", seed=7)
    episode.step({"content": None, "tool_calls": [
        {"id": "c1", "name": "describe_widget", "arguments": {"widget_id": "w1"}}]})
    episode.step({"content": None, "tool_calls": [
        {"id": "c2", "name": "rename_widget", "arguments": {"widget_id": "w1", "label": "striped"}}]})
    out = episode.step({"content": "done", "tool_calls": []})
    assert out.done
    stored = json.loads(json.dumps(as_dict(load_run(episode.run_file())),
                                   ensure_ascii=False, default=str))
    record = episode.run_record()
    assert record["events"] == stored["events"]
    results = [e["payload"]["result"] for e in record["events"] if e.get("type") == "tool_result"]
    assert [r["label"] for r in results] == ["plain", "striped"]


def _drive_one_step(tmp_path):
    root = write_env(tmp_path / "root")
    _write_alias_env(root)
    episode = Episode(BuiltEnvironment(root), outdir=tmp_path / "out")
    episode.reset("widget_task", seed=7)
    episode.step({"content": None, "tool_calls": [
        {"id": "c1", "name": "describe_widget", "arguments": {"widget_id": "w1"}}]})
    return episode


@pytest.mark.parametrize("lose", ["file", "path"])
def test_run_record_missing_file_or_path_with_events_raises(tmp_path, lose):
    episode = _drive_one_step(tmp_path)
    path = episode.run_file()
    if lose == "file":
        path.unlink()
    else:
        # No public way leaves a started Run without a record path; the state is set directly.
        episode._state.path = None
    with pytest.raises(EpisodeError, match="record is missing") as excinfo:
        episode.run_record()
    if lose == "file":
        assert str(path) in str(excinfo.value)
